#!/usr/bin/env bash
# Installs a pre-commit hook that runs the guardrails on every commit.
# Run once per clone:  ./tools/install-hooks.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK" <<'HOOK_BODY'
#!/usr/bin/env bash
# Auto-generated by tools/install-hooks.sh — edit that file instead.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"

echo "pre-commit: guardrails"
python3 "$REPO_ROOT/tools/check_guardrails.py" || {
  echo
  echo "Commit blocked. Fix the violations above, or bypass once with --no-verify"
  echo "(only for a work-in-progress branch, never for main)."
  exit 1
}

# Formatting is cheap to check and annoying to review.
if command -v dart >/dev/null 2>&1 && [ -d "$REPO_ROOT/app" ]; then
  echo "pre-commit: dart format"
  (cd "$REPO_ROOT/app" && dart format --output=none --set-exit-if-changed . ) || {
    echo "Run: cd app && dart format ."
    exit 1
  }
fi
HOOK_BODY

chmod +x "$HOOK"
echo "Installed $HOOK"
echo "Test it with: python3 tools/check_guardrails.py"
